; Generated keycode tables
normal_keycode_table:
db 0x1b ; keycode 0
db 0x00 ; keycode 1
db 0x00 ; keycode 2
db 0x00 ; keycode 3
db 0x00 ; keycode 4
db 0x00 ; keycode 5
db 0x00 ; keycode 6
db 0x00 ; keycode 7
db 0x00 ; keycode 8
db 0x00 ; keycode 9
db 0x00 ; keycode 10
db 0x00 ; keycode 11
db 0x00 ; keycode 12
db 0x00 ; keycode 13
db 0x00 ; keycode 14
db 0x00 ; keycode 15
db 0x60 ; keycode 16, char = '`'
db 0x31 ; keycode 17, char = '1'
db 0x32 ; keycode 18, char = '2'
db 0x33 ; keycode 19, char = '3'
db 0x34 ; keycode 20, char = '4'
db 0x35 ; keycode 21, char = '5'
db 0x36 ; keycode 22, char = '6'
db 0x37 ; keycode 23, char = '7'
db 0x38 ; keycode 24, char = '8'
db 0x39 ; keycode 25, char = '9'
db 0x30 ; keycode 26, char = '0'
db 0x2d ; keycode 27, char = '-'
db 0x3d ; keycode 28, char = '='
db 0x08 ; keycode 29
db 0x00 ; keycode 30
db 0x0d ; keycode 31
db 0x00 ; keycode 32
db 0x00 ; keycode 33
db 0x2f ; keycode 34, char = '/'
db 0x2a ; keycode 35, char = '*'
db 0x2d ; keycode 36, char = '-'
db 0x09 ; keycode 37
db 0x71 ; keycode 38, char = 'q'
db 0x77 ; keycode 39, char = 'w'
db 0x65 ; keycode 40, char = 'e'
db 0x72 ; keycode 41, char = 'r'
db 0x74 ; keycode 42, char = 't'
db 0x79 ; keycode 43, char = 'y'
db 0x75 ; keycode 44, char = 'u'
db 0x69 ; keycode 45, char = 'i'
db 0x6f ; keycode 46, char = 'o'
db 0x70 ; keycode 47, char = 'p'
db 0x5b ; keycode 48, char = '['
db 0x5d ; keycode 49, char = ']'
db 0x5c ; keycode 50, char = '\'
db 0x7f ; keycode 51
db 0x00 ; keycode 52
db 0x00 ; keycode 53
db 0x37 ; keycode 54, char = '7'
db 0x38 ; keycode 55, char = '8'
db 0x39 ; keycode 56, char = '9'
db 0x2b ; keycode 57, char = '+'
db 0x00 ; keycode 58
db 0x61 ; keycode 59, char = 'a'
db 0x73 ; keycode 60, char = 's'
db 0x64 ; keycode 61, char = 'd'
db 0x66 ; keycode 62, char = 'f'
db 0x67 ; keycode 63, char = 'g'
db 0x68 ; keycode 64, char = 'h'
db 0x6a ; keycode 65, char = 'j'
db 0x6b ; keycode 66, char = 'k'
db 0x6c ; keycode 67, char = 'l'
db 0x3b ; keycode 68, char = ';'
db 0x27 ; keycode 69, char = '''
db 0x0a ; keycode 70
db 0x34 ; keycode 71, char = '4'
db 0x35 ; keycode 72, char = '5'
db 0x36 ; keycode 73, char = '6'
db 0x00 ; keycode 74
db 0x7a ; keycode 75, char = 'z'
db 0x78 ; keycode 76, char = 'x'
db 0x63 ; keycode 77, char = 'c'
db 0x76 ; keycode 78, char = 'v'
db 0x62 ; keycode 79, char = 'b'
db 0x6e ; keycode 80, char = 'n'
db 0x6d ; keycode 81, char = 'm'
db 0x2c ; keycode 82, char = ','
db 0x2e ; keycode 83, char = '.'
db 0x2f ; keycode 84, char = '/'
db 0x00 ; keycode 85
db 0x00 ; keycode 86
db 0x31 ; keycode 87, char = '1'
db 0x32 ; keycode 88, char = '2'
db 0x33 ; keycode 89, char = '3'
db 0x0a ; keycode 90
db 0x00 ; keycode 91
db 0x00 ; keycode 92
db 0x00 ; keycode 93
db 0x20 ; keycode 94, char = ' '
db 0x00 ; keycode 95
db 0x00 ; keycode 96
db 0x00 ; keycode 97
db 0x00 ; keycode 98
db 0x00 ; keycode 99
db 0x00 ; keycode 100
db 0x30 ; keycode 101, char = '0'
db 0x2e ; keycode 102, char = '.'
alt_keycode_table:
db 0x1b ; keycode 0
db 0x00 ; keycode 1
db 0x00 ; keycode 2
db 0x00 ; keycode 3
db 0x00 ; keycode 4
db 0x00 ; keycode 5
db 0x00 ; keycode 6
db 0x00 ; keycode 7
db 0x00 ; keycode 8
db 0x00 ; keycode 9
db 0x00 ; keycode 10
db 0x00 ; keycode 11
db 0x00 ; keycode 12
db 0x00 ; keycode 13
db 0x00 ; keycode 14
db 0x00 ; keycode 15
db 0x7e ; keycode 16, char = '~'
db 0x21 ; keycode 17, char = '!'
db 0x40 ; keycode 18, char = '@'
db 0x23 ; keycode 19, char = '#'
db 0x24 ; keycode 20, char = '$'
db 0x25 ; keycode 21, char = '%'
db 0x5e ; keycode 22, char = '^'
db 0x26 ; keycode 23, char = '&'
db 0x2a ; keycode 24, char = '*'
db 0x28 ; keycode 25, char = '('
db 0x29 ; keycode 26, char = ')'
db 0x5f ; keycode 27, char = '_'
db 0x2b ; keycode 28, char = '+'
db 0x08 ; keycode 29
db 0x00 ; keycode 30
db 0x0d ; keycode 31
db 0x00 ; keycode 32
db 0x00 ; keycode 33
db 0x2f ; keycode 34, char = '/'
db 0x2a ; keycode 35, char = '*'
db 0x2d ; keycode 36, char = '-'
db 0x09 ; keycode 37
db 0x51 ; keycode 38, char = 'Q'
db 0x57 ; keycode 39, char = 'W'
db 0x45 ; keycode 40, char = 'E'
db 0x52 ; keycode 41, char = 'R'
db 0x54 ; keycode 42, char = 'T'
db 0x59 ; keycode 43, char = 'Y'
db 0x55 ; keycode 44, char = 'U'
db 0x49 ; keycode 45, char = 'I'
db 0x4f ; keycode 46, char = 'O'
db 0x50 ; keycode 47, char = 'P'
db 0x7b ; keycode 48, char = '{'
db 0x7d ; keycode 49, char = '}'
db 0x7c ; keycode 50, char = '|'
db 0x7f ; keycode 51
db 0x00 ; keycode 52
db 0x00 ; keycode 53
db 0x37 ; keycode 54, char = '7'
db 0x38 ; keycode 55, char = '8'
db 0x39 ; keycode 56, char = '9'
db 0x2b ; keycode 57, char = '+'
db 0x00 ; keycode 58
db 0x41 ; keycode 59, char = 'A'
db 0x53 ; keycode 60, char = 'S'
db 0x44 ; keycode 61, char = 'D'
db 0x46 ; keycode 62, char = 'F'
db 0x47 ; keycode 63, char = 'G'
db 0x48 ; keycode 64, char = 'H'
db 0x4a ; keycode 65, char = 'J'
db 0x4b ; keycode 66, char = 'K'
db 0x4c ; keycode 67, char = 'L'
db 0x3a ; keycode 68, char = ':'
db 0x22 ; keycode 69, char = '"'
db 0x0a ; keycode 70
db 0x34 ; keycode 71, char = '4'
db 0x35 ; keycode 72, char = '5'
db 0x36 ; keycode 73, char = '6'
db 0x00 ; keycode 74
db 0x5a ; keycode 75, char = 'Z'
db 0x58 ; keycode 76, char = 'X'
db 0x43 ; keycode 77, char = 'C'
db 0x56 ; keycode 78, char = 'V'
db 0x42 ; keycode 79, char = 'B'
db 0x4e ; keycode 80, char = 'N'
db 0x4d ; keycode 81, char = 'M'
db 0x3c ; keycode 82, char = '<'
db 0x3e ; keycode 83, char = '>'
db 0x3f ; keycode 84, char = '?'
db 0x00 ; keycode 85
db 0x00 ; keycode 86
db 0x31 ; keycode 87, char = '1'
db 0x32 ; keycode 88, char = '2'
db 0x33 ; keycode 89, char = '3'
db 0x0a ; keycode 90
db 0x00 ; keycode 91
db 0x00 ; keycode 92
db 0x00 ; keycode 93
db 0x20 ; keycode 94, char = ' '
db 0x00 ; keycode 95
db 0x00 ; keycode 96
db 0x00 ; keycode 97
db 0x00 ; keycode 98
db 0x00 ; keycode 99
db 0x00 ; keycode 100
db 0x00 ; keycode 101
db 0x00 ; keycode 102
